version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_ceps
    restart: always
    environment:
      POSTGRES_DB: ceps
      POSTGRES_USER: cepuser
      POSTGRES_PASSWORD: ceppass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  mongodb:
    image: mongo:7
    container_name: mongo_ceps
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
